name: Commit Check

on:
  push:
    branches:
      - main
      - 'main/**' # Optional: You can specify specific directories if needed

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Verify Commit Message
        run: |
          if [[ $GITHUB_REF != 'refs/heads/main' ]]; then
            if ! git log -1 --pretty=%B | grep -q '[A-Z]+-[0-9]+'; then
              echo "Error: Jira ticket ID not found in the commit message."
              exit 1
            fi
          fi

